### ISSUE TITLE
Mis/disinformation link is broken

### ISSUE THREAD

**Issue by milesmcc** [badnessdotai/catalog#59]
https://badness.ai/categories/Mis%2Fdisinformation

No clue how this happened:

<img width="2303" alt="image" src="https://user-images.githubusercontent.com/3037552/229954787-ed4b8ac5-2ef0-4197-967e-186ae78a6b60.png">

**Comment by coderrg** [comment]
Fixed in https://github.com/badnessdotai/catalog/commit/71c70b6779e7e4126cd50f25a4caf4bb652e0d3a
